
//////////////////// STRINGS

const Strings = {

    "ST1": "Fooood",
    "ST2": "Home",
    "ST3": "Search",
    "S4": "Members",
    "ST5": "Profile",
    "ST6": "Sign Out",
    "ST7": "Sign In",
    "ST8": "Sign Up",
    "ST9": "Don't have an account?",
    "ST10": "Already have an account?",
    "ST11": "I Agree to Terms and Conditions",
    "ST12": "Forgot Password?",
    "ST13": "Need Help? Contact Us",
    "ST14": "Enter",
    "ST15": "Name",
    "ST16": "Email",
    "ST17": "Password",
    "ST18": "Real Food. Real Simple",
    "ST19": "MyFeed",
    "ST20": "No Content Found",
    "ST21": "Please Wait...",
    "ST22": "Something Wrong",
    "ST23": "Please Complete The Form",
    "ST24": "Sign In",
    "ST25": "Sign Up",
    "ST26": "Email Already Exists",
    "ST27": "Email Doesn't Exist",
    "ST28": "Password Updated",
    "ST29": "Password Reset Email Sent",
    "ST30": "Ok",
    "ST31": "Need Help?",
    "ST32": "Contact Us",
    "ST33": "Reset Password",
    "ST34": "Any",
    "ST35": "Servings",
    "ST36": "Ingredients",
    "ST37": "No Results Found",
    "ST38": "Instructions",
    "ST39": "By",
    "ST40": "No content in this feed",
    "ST41": "Try Again",
    "ST42": "Done",
    "ST43": "Cancel",
    "ST44": "Save",
    "ST45": "Description",
    "ST46": "Comments",
    "ST47": "Show Comments",
    "ST48": "No Comments Found",
    "ST49": "Submit Comment",
    "ST50": "Share",
    "ST52": "Submit",
    "ST52": "Thank You",
    "ST53": "Your message has been submitted",
    "ST54": "Your message could not be sent",
    "ST55": "Get In Touch",
    "ST56": "Use the form below to drop us an e-mail",
    "ST57": "View other replies",
    "ST58": "Your Comment",
    "ST59": "Error",
    

};

export default Strings;
